version: "3"
services: 
    frontend:
        build: "./frontend"
        ports:
            - 3000:3000
        volumes: 
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
        environment: 
            - CHOKIDAR_USEPOLLING=true
    backend:
        build: "./backend"
        ports:
            - 5000:5000
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        links:
            - frontend
        volumes: 
            - ./nginx:/etc/nginx/conf.d
    mongo:
        image: mongo
        ports:
            - 27017:27017